import { NextResponse } from "next/server";

const links = [
  { title: 'Namaste Javascript', content: 'https://www.youtube.com/playlist?list=PLlasXeu85E9cQ32gLCvAvr9vNaUccPVNP' },
  { title: 'Computer Networking: Jim Kurose', content: 'https://www.youtube.com/watch?v=74sEFYBBRAY' },
  { title: 'Computer Networking: Top-Down Approach Book', content: 'https://archive.org/details/computernetworki0000jame_y6m8' },
  { title: 'Computer Networking: Teaching Material', content: 'https://gaia.cs.umass.edu/kurose_ross/videos/1/' },
  { title: 'Mermaid Chart', content: 'https://www.mermaidchart.com/' },
  { title: 'Egghead React', content: 'https://egghead.io/q/react' },
  { title: 'Eloquent JavaScript Ebook', content: 'https://eloquentjavascript.net/01_values.html' },
  { title: 'Modern Javascript Tutorial', content: 'https://javascript.info/' },
  { title: 'You Don\'t Know JS Yet', content: 'https://github.com/getify/You-Dont-Know-JS/tree/2nd-ed/es-next-beyond' },
  { title: 'Egghead React Hooks', content: 'https://egghead.io/lessons/react-introduction-to-refactoring-a-react-application-to-react-hooks' },
  { title: 'Functional Programming in JS', content: 'https://www.youtube.com/playlist?list=PL0zVEGEvSaeEd9hlmCXrk5yUyqUag-n84' },
  { title: 'Fullstack Helenski University', content: 'https://fullstackopen.com/en/part2/getting_data_from_server' },
  { title: 'UMASO Coolors', content: 'https://coolors.co/201b44-512889-4f45aa-655f92-42bfdd' },
  { title: 'The Odin Project: Vanilla Web Dev', content: 'https://www.theodinproject.com/paths/foundations/courses/foundations' },
  { title: 'Github - Project Based Learning', content: 'https://github.com/practical-tutorials/project-based-learning?tab=readme-ov-file' },
  { title: 'SST.dev', content: 'https://sst.dev/' },
  { title: 'SkillMill - BPL', content: 'https://bpl.libwizard.com/f/skillmill' },
  { title: 'Animate.CSS', content: 'https://animate.style/' },
  { title: 'Front CSS Lib', content: 'https://htmlstream.com/preview/front-v3.2/documentation/svg-divider.html' },
  { title: 'Tailwind.css', content: 'https://tailwindcss.com/docs/responsive-design' },
  { title: 'DuckTyped: AWS Networking', content: 'https://www.ducktyped.org/p/a-mini-book-on-aws-networking-introduction' },
  { title: 'DuckTyped: Archive', content: 'https://www.ducktyped.org/archive' },
  { title: 'Leafo.net', content: 'https://leafo.net/' },
  { title: 'Linear Algebra - Gilbert Strang', content: 'https://www.youtube.com/watch?v=QVKj3LADCnA&list=PL49CF3715CB9EF31D' },
  { title: 'Linear Algebra Done Right Book', content: 'https://library.oapen.org/viewer/web/viewer.html?file=/bitstream/handle/20.500.12657/85067/978-3-031-41026-0.pdf?sequence=1&isAllowed=y' },
  { title: 'Khan Academy: Linear Algebra', content: 'https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces' },
  { title: 'Problem Solving With Algorithms and Data Structures Using Python', content: 'https://github.com/wesleyjtann/Problem-Solving-with-Algorithms-and-Data-Structures-Using-Python/blob/master/Problem-Solving-with-Algorithms-and-Data-Structures-Using-Python-SECOND-EDITION.pdf' },
  { title: 'Github: Cool Project Ideas', content: 'https://github.com/The-Cool-Coders/Project-Ideas-And-Resources' },
  { title: 'CICS Events', content: 'https://www.cics.umass.edu/events?page=0' },
  { title: 'Popular Tech Skills - Dice', content: 'https://www.dice.com/technologists/ebooks/tech-job-report/skills.html' },
  { title: 'CICS Undergraduate Research Opportunities', content: 'https://www.cics.umass.edu/research/undergraduate-research-opportunities' },
  { title: 'Summer of Code', content: 'https://summerofcode.withgoogle.com/programs/2025/organizations' },
  { title: 'Cybersecurity: Digital Evidence Lab', content: 'https://cyber.cs.umass.edu/news/digital-evidence-lab' },
  { title: 'Cybersec Club', content: 'https://umasscybersec.org/' },
  { title: 'Machine Learning Club', content: 'https://umass.acm.org/sigs/Machine-Learning' },
  { title: 'Career Forge - Career Advising', content: 'https://careerforge.us/login?m=login' },
  { title: 'CICS Notion', content: 'https://cicscareers.notion.site/Decide-What-Matters-0c62b40b808640dc99071a72cf02e71e' },
  { title: 'Cracking the Coding Interview', content: 'https://www.crackingthecodinginterview.com/' },
  { title: 'UMASS ERSP', content: 'https://sites.google.com/umass.edu/ersp-cics' },
  { title: 'Mystery Train Blog', content: 'https://poptropi.ca/island-help/mystery-train/' },
  { title: 'Mystery Train Sprite Sheet', content: 'https://www.google.com/search?q=poptropica+sprite+sheet+mystery+train&sca_esv=8728115b13c098f3&udm=2&biw=1440&bih=812&sxsrf=AHTn8zrH_wvsIFiw53bqk_OyY-phjRGO1g%3A1747513284392&ei=xO8oaIrbF83m5NoPts2SmA0&ved=0ahUKEwiKzbmkqquNAxVNM1kFHbamBNMQ4dUDCBE&uact=5&oq=poptropica+sprite+sheet+mystery+train&gs_lp=EgNpbWciJXBvcHRyb3BpY2Egc3ByaXRlIHNoZWV0IG15c3RlcnkgdHJhaW5Ii11Q-SNY8FdwA3gAkAEAmAG_AaAB6QqqAQQxNi4yuAEDyAEA-AEBmAIEoALiAsICBxAjGCcYyQLCAgUQABiABJgDAIgGAZIHAzMuMaAHpyCyBwMzLjG4B-ICwgcDMi00yAcS&sclient=img#vhid=1i9z37euNX8mIM&vssid=mosaic' },
  { title: 'Mystery Train Compartments', content: 'https://poptropica.fandom.com/wiki/Coach_Car' },
  { title: 'Poptropica Sprites', content: 'https://www.google.com/search?sca_esv=8728115b13c098f3&sxsrf=AHTn8zrdF4TRoCNCHBZelh5PTpp9Ao-hGg:1747513777963&q=poptropica+sprites&udm=2&fbs=ABzOT_CWdhQLP1FcmU5B0fn3xuWpA-dk4wpBWOGsoR7DG5zJBkzPWUS0OtApxR2914vrjk4ZqZZ4I2IkJifuoUeV0iQtlsVaSqiwnznvC1owt2z2tTdc23Auc6X4y2i7IIF0f-daFQAnIISUeBdGNO3Bl2VmXrYULqbJwOFxhGBxjDvPi7AXljWm69dCJGJtZf49EuPbm-5He1d5dYd0SRT0i0ep72Wwyw&sa=X&ved=2ahUKEwj-4uaPrKuNAxXQM1kFHTwFMwIQtKgLegQIFBAB&biw=1440&bih=812&dpr=2#vhid=s6-LQj4xPog5VM&vssid=mosaic' },
  { title: 'FreeCodeCamp Frontend', content: 'https://www.freecodecamp.org/learn/front-end-development-libraries/' },
  { title: 'Leetcode', content: 'https://leetcode.com/accounts/login/' },
  { title: 'CICS Career Community', content: 'https://cicscareercommunity.slack.com/?redir=%2Farchives%2FCC63TUHGV%2Fp1749661362000119%3Fname%3DCC63TUHGV%26perma%3D1749661362000119' },
  { title: 'FontAwesome', content: 'https://docs.fontawesome.com/web/setup/use-kit' },
];

export async function GET() {
    return NextResponse.json(links);
}