import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import SessionWrapper from "../components/sessionWrapper";

export const metadata: Metadata = {
  title: "Link Database",
  description: "Generated by create next app",
};

const rubik = Rubik({subsets: ['latin']});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" className={rubik.className}>
      <body>
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
